import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Poetsen_One } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./Components/Navbar";

const poetsenOne = Poetsen_One({
  subsets: ["latin"],  // required
  weight: "400",       // Poetsen One only has one weight (400)
  variable: "--font-poetsenOne",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Khata Book",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg', // Specify the path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${poetsenOne.className} antialiased`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
